<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DeliveryZoneSeeder extends Seeder
{
    /**
     * Delivery price matrix.
     * Structure: pickup_zone => [ delivery_zone => price ]
     *
     * "Not Included" is the fallback used when a seller's zone
     * is not in the known pickup zones list.
     */
    private array $matrix = [
        'Mayfair' => [
            'Parakin'           => 800,
            'Sabo'              => 1300,
            'Aderemi Road'      => 1200,
            'Ondo Road'         => 2500,
            'Lagere'            => 800,
            'Moore'             => 1600,
            'Opa'               => 2400,
            'Iremo'             => 1300,
            'Ilode'             => 2500,
            'Ajebamidele'       => 1000,
            'Omole'             => 800,
            'OAU Staff Quarters'=> 1200,
            'OAUTHC'            => 1800,
            'Damico'            => 1000,
            'Eleyele'           => 900,
            'Asherifa'          => 900,
            'Oduduwa'           => 800,
            'Moremi Estate'     => 800,
            'Power line'        => 1000,
            'Campus gate'       => 800,
            'Campus'            => 1000,
            'AP'                => 800,
            'Maintenance'       => 800,
            'Ojaja hostel'      => 1000,
            'Fashina'           => 1500,
            'Oonilayout'        => 1000,
            'Akarabata'         => 800,
            'Road 7'            => 1200,
            'Modomo'            => 1200,
            'Nasfat'            => 1400,
        ],

        'Lagere' => [
            'Parakin'           => 800,
            'Sabo'              => 1300,
            'Aderemi Road'      => 1200,
            'Ondo Road'         => 2500,
            'Lagere'            => 800,
            'Moore'             => 1600,
            'Opa'               => 2400,
            'Iremo'             => 1300,
            'Ilode'             => 2500,
            'Ajebamidele'       => 1000,
            'Omole'             => 800,
            'OAU Staff Quarters'=> 1200,
            'OAUTHC'            => 1800,
            'Damico'            => 1000,
            'Eleyele'           => 900,
            'Asherifa'          => 900,
            'Oduduwa'           => 800,
            'Moremi Estate'     => 800,
            'Power line'        => 1000,
            'Campus gate'       => 800,
            'Campus'            => 1000,
            'AP'                => 800,
            'Maintenance'       => 800,
            'Ojaja hostel'      => 1000,
            'Fashina'           => 1500,
            'Oonilayout'        => 1000,
            'Akarabata'         => 800,
            'Road 7'            => 1200,
            'Modomo'            => 1200,
            'Nasfat'            => 1400,
        ],

        'OAUTHC' => [
            'Parakin'           => 1800,
            'Sabo'              => 1700,
            'Aderemi Road'      => 1700,
            'Ondo Road'         => 2700,
            'Lagere'            => 1700,
            'Moore'             => 1700,
            'Opa'               => 2500,
            'Iremo'             => 1800,
            'Ilode'             => 2500,
            'Ajebamidele'       => 2000,
            'Omole'             => 1700,
            'OAU Staff Quarters'=> 1800,
            'OAUTHC'            => 2000,
            'Damico'            => 1900,
            'Eleyele'           => 1700,
            'Asherifa'          => 1800,
            'Oduduwa'           => 1800,
            'Moremi Estate'     => 1800,
            'Power line'        => 1900,
            'Campus gate'       => 1700,
            'Campus'            => 1700,
            'AP'                => 1800,
            'Maintenance'       => 1700,
            'Ojaja hostel'      => 1700,
            'Fashina'           => 2550,  // Note: source listed 25500, assumed typo for 2550
            'Oonilayout'        => 2000,
            'Akarabata'         => 1800,
            'Road 7'            => 1700,
            'Modomo'            => 2000,
            'Nasfat'            => 2300,
        ],

        'Damico' => [
            'Parakin'           => 1000,
            'Sabo'              => 1500,
            'Aderemi Road'      => 1400,
            'Ondo Road'         => 2500,
            'Lagere'            => 1200,
            'Moore'             => 1800,
            'Opa'               => 2500,
            'Iremo'             => 1600,
            'Ilode'             => 2500,
            'Ajebamidele'       => 800,
            'Omole'             => 1000,
            'OAU Staff Quarters'=> 1200,
            'OAUTHC'            => 2000,
            'Damico'            => 800,
            'Eleyele'           => 1300,
            'Asherifa'          => 900,
            'Oduduwa'           => 800,
            'Moremi Estate'     => 900,
            'Power line'        => 800,
            'Campus gate'       => 800,
            'Campus'            => 1000,
            'AP'                => 1000,
            'Maintenance'       => 800,
            'Ojaja hostel'      => 1000,
            'Fashina'           => 1200,
            'Oonilayout'        => 800,
            'Akarabata'         => 1200,
            'Road 7'            => 1400,
            'Modomo'            => 900,
            'Nasfat'            => 1200,
        ],

        'Campus' => [
            'Parakin'           => 1000,
            'Sabo'              => 1500,
            'Aderemi Road'      => 1400,  // Note: source listed 14000, assumed typo for 1400
            'Ondo Road'         => 2500,
            'Lagere'            => 1200,
            'Moore'             => 1800,
            'Opa'               => 2500,
            'Iremo'             => 1600,
            'Ilode'             => 2500,
            'Ajebamidele'       => 1000,
            'Omole'             => 1000,
            'OAU Staff Quarters'=> 700,
            'OAUTHC'            => 1800,
            'Damico'            => 1000,
            'Eleyele'           => 1300,
            'Asherifa'          => 1000,
            'Oduduwa'           => 900,
            'Moremi Estate'     => 1000,
            'Power line'        => 1000,
            'Campus gate'       => 800,
            'Campus'            => 700,
            'AP'                => 1000,
            'Maintenance'       => 800,
            'Ojaja hostel'      => 700,
            'Fashina'           => 1500,
            'Oonilayout'        => 1000,
            'Akarabata'         => 1200,
            'Road 7'            => 1200,
            'Modomo'            => 1200,
            'Nasfat'            => 1400,
        ],

        'Asherifa' => [
            'Parakin'           => 900,
            'Sabo'              => 1500,
            'Aderemi Road'      => 1400,
            'Ondo Road'         => 2500,
            'Lagere'            => 1100,
            'Moore'             => 1800,
            'Opa'               => 2500,
            'Iremo'             => 1500,
            'Ilode'             => 2500,
            'Ajebamidele'       => 900,
            'Omole'             => 900,
            'OAU Staff Quarters'=> 1200,
            'OAUTHC'            => 1900,
            'Damico'            => 900,
            'Eleyele'           => 1100,
            'Asherifa'          => 800,
            'Oduduwa'           => 800,
            'Moremi Estate'     => 800,
            'Power line'        => 900,
            'Campus gate'       => 800,
            'Campus'            => 1000,
            'AP'                => 900,
            'Maintenance'       => 800,
            'Ojaja hostel'      => 1000,
            'Fashina'           => 1400,
            'Oonilayout'        => 900,
            'Akarabata'         => 1000,
            'Road 7'            => 1200,
            'Modomo'            => 1200,
            'Nasfat'            => 1400,
        ],

        'Oduduwa' => [
            'Parakin'           => 800,
            'Sabo'              => 1500,
            'Aderemi Road'      => 1400,
            'Ondo Road'         => 2500,
            'Lagere'            => 1000,
            'Moore'             => 1800,
            'Opa'               => 2500,
            'Iremo'             => 1500,
            'Ilode'             => 2500,
            'Ajebamidele'       => 800,
            'Omole'             => 900,
            'OAU Staff Quarters'=> 1100,
            'OAUTHC'            => 1800,
            'Damico'            => 800,
            'Eleyele'           => 1100,
            'Asherifa'          => 800,
            'Oduduwa'           => 800,
            'Moremi Estate'     => 800,
            'Power line'        => 800,
            'Campus gate'       => 800,
            'Campus'            => 900,
            'AP'                => 900,
            'Maintenance'       => 700,
            'Ojaja hostel'      => 900,
            'Fashina'           => 1400,
            'Oonilayout'        => 800,
            'Akarabata'         => 1000,
            'Road 7'            => 1200,
            'Modomo'            => 1000,
            'Nasfat'            => 1200,
        ],

        'Moremi' => [
            'Parakin'           => 900,
            'Sabo'              => 1500,
            'Aderemi Road'      => 1400,
            'Ondo Road'         => 2500,
            'Lagere'            => 1100,
            'Moore'             => 1800,
            'Opa'               => 2500,
            'Iremo'             => 1500,
            'Ilode'             => 2500,
            'Ajebamidele'       => 900,
            'Omole'             => 900,
            'OAU Staff Quarters'=> 1200,
            'OAUTHC'            => 1900,
            'Damico'            => 900,
            'Eleyele'           => 1100,
            'Asherifa'          => 800,
            'Oduduwa'           => 800,
            'Moremi Estate'     => 800,
            'Power line'        => 900,
            'Campus gate'       => 800,
            'Campus'            => 1000,
            'AP'                => 900,
            'Maintenance'       => 800,
            'Ojaja hostel'      => 1000,
            'Fashina'           => 1400,
            'Oonilayout'        => 900,
            'Akarabata'         => 1000,
            'Road 7'            => 1200,
            'Modomo'            => 1200,
            'Nasfat'            => 1400,
        ],

        'Maintenance' => [
            'Parakin'           => 1000,
            'Sabo'              => 1500,
            'Aderemi Road'      => 1400,  // Note: source listed 14000, assumed typo for 1400
            'Ondo Road'         => 2500,
            'Lagere'            => 1200,
            'Moore'             => 1800,
            'Opa'               => 2500,
            'Iremo'             => 1600,
            'Ilode'             => 2500,
            'Ajebamidele'       => 1000,
            'Omole'             => 1000,
            'OAU Staff Quarters'=> 700,
            'OAUTHC'            => 1800,
            'Damico'            => 1000,
            'Eleyele'           => 1300,
            'Asherifa'          => 1000,
            'Oduduwa'           => 900,
            'Moremi Estate'     => 1000,
            'Power line'        => 1000,
            'Campus gate'       => 800,
            'Campus'            => 700,
            'AP'                => 1000,
            'Maintenance'       => 800,
            'Ojaja hostel'      => 700,
            'Fashina'           => 1500,
            'Oonilayout'        => 1000,
            'Akarabata'         => 1200,
            'Road 7'            => 1200,
            'Modomo'            => 1200,
            'Nasfat'            => 1400,
        ],

        'Oonilayout' => [
            'Parakin'           => 1000,
            'Sabo'              => 1500,
            'Aderemi Road'      => 1400,
            'Ondo Road'         => 2500,
            'Lagere'            => 1200,
            'Moore'             => 1800,
            'Opa'               => 2500,
            'Iremo'             => 1600,
            'Ilode'             => 2500,
            'Ajebamidele'       => 800,
            'Omole'             => 1000,
            'OAU Staff Quarters'=> 1200,
            'OAUTHC'            => 2000,
            'Damico'            => 800,
            'Eleyele'           => 1300,
            'Asherifa'          => 900,
            'Oduduwa'           => 800,
            'Moremi Estate'     => 900,
            'Power line'        => 800,
            'Campus gate'       => 800,
            'Campus'            => 1000,
            'AP'                => 1000,
            'Maintenance'       => 800,
            'Ojaja hostel'      => 1000,
            'Fashina'           => 1200,
            'Oonilayout'        => 800,
            'Akarabata'         => 1200,
            'Road 7'            => 1400,
            'Modomo'            => 900,
            'Nasfat'            => 1200,
        ],

        'Fashina' => [
            'Parakin'           => 1000,
            'Sabo'              => 1500,
            'Aderemi Road'      => 1400,
            'Ondo Road'         => 2500,
            'Lagere'            => 1200,
            'Moore'             => 1800,
            'Opa'               => 2500,
            'Iremo'             => 1600,
            'Ilode'             => 2500,
            'Ajebamidele'       => 800,
            'Omole'             => 1000,
            'OAU Staff Quarters'=> 1200,
            'OAUTHC'            => 2000,
            'Damico'            => 800,
            'Eleyele'           => 1300,
            'Asherifa'          => 900,
            'Oduduwa'           => 800,
            'Moremi Estate'     => 900,
            'Power line'        => 800,
            'Campus gate'       => 800,
            'Campus'            => 1000,
            'AP'                => 1000,
            'Maintenance'       => 800,
            'Ojaja hostel'      => 1000,
            'Fashina'           => 1200,
            'Oonilayout'        => 800,
            'Akarabata'         => 1200,
            'Road 7'            => 1400,
            'Modomo'            => 900,
            'Nasfat'            => 1200,
        ],

        // Fallback: used when the seller's pickup zone is not in the list above
        'Not Included' => [
            'Parakin'           => 1800,
            'Sabo'              => 1700,
            'Aderemi Road'      => 1700,
            'Ondo Road'         => 2700,
            'Lagere'            => 1700,
            'Moore'             => 1700,
            'Opa'               => 2500,
            'Iremo'             => 1800,
            'Ilode'             => 2500,
            'Ajebamidele'       => 2000,
            'Omole'             => 1700,
            'OAU Staff Quarters'=> 1800,
            'OAUTHC'            => 2000,
            'Damico'            => 1900,
            'Eleyele'           => 1700,
            'Asherifa'          => 1800,
            'Oduduwa'           => 1800,
            'Moremi Estate'     => 1800,
            'Power line'        => 1900,
            'Campus gate'       => 1700,
            'Campus'            => 1700,
            'AP'                => 1800,
            'Maintenance'       => 1700,
            'Ojaja hostel'      => 1700,
            'Fashina'           => 2550,
            'Oonilayout'        => 2000,
            'Akarabata'         => 1800,
            'Road 7'            => 1700,
            'Modomo'            => 2000,
            'Nasfat'            => 2300,
        ],
    ];

    public function run(): void
    {
        // Clear existing data before re-seeding
        DB::table('delivery_zones')->truncate();

        $rows = [];
        $now  = now();

        foreach ($this->matrix as $pickupZone => $destinations) {
            foreach ($destinations as $deliveryZone => $price) {
                $rows[] = [
                    'pickup_zone'   => $pickupZone,
                    'delivery_zone' => $deliveryZone,
                    'price'         => $price,
                    'created_at'    => $now,
                    'updated_at'    => $now,
                ];
            }
        }

        // Insert in one query for efficiency
        DB::table('delivery_zones')->insert($rows);

        $this->command->info('Delivery zones seeded: ' . count($rows) . ' rows across ' . count($this->matrix) . ' pickup zones.');
    }
}